### ISSUE TITLE
Address family not supported by protocol (os error 97)

### ISSUE THREAD

**Issue by Abu-Abdullah** [joseluisq/static-web-server#134] opened 2022-08-19 15:58 UTC
Hi,

server will not start if ipv6 is disabled
```
ERROR static_web_server::server: server failed to start up: failed to bind to [::]:8787 address
Caused by:
    Address family not supported by protocol (os error 97)
```

it might be better to have a switch to disable ipv6 or at least handle such error in case ipv6 is not loaded

and thank you for this library

**Comment by joseluisq** [comment] 2022-08-20 05:46
I think you mean to default to the available protocol. If so then looks more like a enhancement for me.

**Comment by mac-chaffee** [comment] 2023-04-19 21:37
The quick fix is to explicitly pass `--host 0.0.0.0` or similarly could set `SERVER_HOST=0.0.0.0` or put `host = "0.0.0.0"` in your config file. That will override the default value of `::`.

After doing [a little reading](https://unix.stackexchange.com/questions/663611/getting-ipv4-ipv6-dual-stack-servers-to-bind-to-0-0-0-0-instead-of-on-machine), I think the default value of `::` should stay. That allows SWS to support IPv6-only servers, dual-stack servers, and servers that don't explicitly disable IPv6 without requiring custom detection code (the OS takes care of it for us). 

I've only heard of disabling IPv6 being recommended by the [CIS Benchmarks](https://www.cisecurity.org/cis-benchmarks) for extra security (not having to manage 2 firewall rulesets), but like all things in security, it's comes with the tradeoff of lower compatibility. If that just means users have to add an extra flag, that's seems like an acceptable price to pay. This is coming from me, someone who runs a lot of CIS-hardened VMs with IPv6 disabled :)

**Comment by mac-chaffee** [comment] 2023-04-19 21:42
Oh I forgot to mention: I actually came across this issue when I was seeing the same error for a different reason. I was trying to run SWS in systemd with a bunch of sandboxing enabled. This error can also appear if you've restricted SWS's systemd unit too much, like not allowing ` AF_INET6` in `RestrictAddressFamilies` or an overly-restrictive `SystemCallFilter`.

Just putting it here for future debuggers!

**Comment by joseluisq** [comment] 2023-04-19 21:58
@mac-chaffee thanks for your insights.

In fact, I was also thinking that effectively, it should be fair enough to just adjust the server host in such scenarios.

On the other hand. Honestly, I do not have a clue if we should or not auto-detect the underlying protocol. 
What we could improve for sure, is handling the error and making it more obvious.

**Comment by joseluisq** [comment] 2023-06-07 10:35
BTW I just labeled the issue as `not-a-bug` and going to close it since it's an SWS-expected behavior. 
Therefore, adjusting the `port` option should be fair enough as already explained by https://github.com/static-web-server/static-web-server/issues/134#issuecomment-1515418054.

That said, defaulting to an unspecified IPv6 address (a.k.a. `::`) seems to be a safe bed for today and [even tomorrow](https://www.internetsociety.org/deploy360/ipv6/faq/).

If you feel that we can improve our error handling and make it more obvious, please feel free to help.

**Closed as completed by joseluisq** 2023-06-07 10:35 UTC
Labels: v2, not-a-bug
