### ISSUE TITLE
Cache Issues

### ISSUE THREAD

**Issue by tuta-amb** [joseluisq/static-web-server#280] opened 2023-11-03 16:25 UTC
I'm using this as a development server, however I'm running into the major issue that the files are being cached. I'm not sure exactly what is happening, but it seems like my linked JS Module files are being cached and the new versions are not being served. This is my configuration file:
```toml
[general]
port = 8080
host = "::"
root = "./src"
log-level = "trace"
cache-control-headers = false
compression = false
page404 = "./src/404.html"
page50x = "./src/500.html"
page-fallback = "./src/index.html"
directory-listing = true
log-remote-address = true
ignore-hidden-files = true
redirect-trailing-slash = true

[[advanced.headers]]
source = "*"
[advanced.headers.headers]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"
```
I've tried to add cache headers but the files are still not being updated. The only solution that I can use is to manually use my browser to visit the script file locations, which then updates the cache.

**Comment by joseluisq** [comment] 2023-11-03 17:54
> I've tried to add cache headers but the files are still not being updated. The only solution that I can use is to manually use my browser to visit the script file locations, which then updates the cache.

Probably the headers are not also applied.
Just try to wrap the source glob pattern with curly braces like `source = "{*}"`. That should work.

**Comment by joseluisq** [comment] 2023-11-14 21:52
I did a quick test of your configuration settings and the JS files that I used in my HTML page get updated and the headers are present as well in the response.

It looks like your problem is not related to SWS per se. So I'm going to close the issue.
If you want to discuss this further or if you have a better way to reproduce your issue just me know.

**Closed as completed by joseluisq** 2023-11-14 21:52 UTC
Labels: not-a-bug
